/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/authorization/LoginView': RouteRecordInfo<'/authorization/LoginView', '/authorization/LoginView', Record<never, never>, Record<never, never>>,
    '/authorization/LogoutView': RouteRecordInfo<'/authorization/LogoutView', '/authorization/LogoutView', Record<never, never>, Record<never, never>>,
    '/authorization/SignupInvitationView': RouteRecordInfo<'/authorization/SignupInvitationView', '/authorization/SignupInvitationView', Record<never, never>, Record<never, never>>,
    '/authorization/SignupView': RouteRecordInfo<'/authorization/SignupView', '/authorization/SignupView', Record<never, never>, Record<never, never>>,
    '/dashboard/DashboardView': RouteRecordInfo<'/dashboard/DashboardView', '/dashboard/DashboardView', Record<never, never>, Record<never, never>>,
    '/members/MembersView': RouteRecordInfo<'/members/MembersView', '/members/MembersView', Record<never, never>, Record<never, never>>,
    '/projects/ProjectDetailsView': RouteRecordInfo<'/projects/ProjectDetailsView', '/projects/ProjectDetailsView', Record<never, never>, Record<never, never>>,
    '/projects/ProjectsView': RouteRecordInfo<'/projects/ProjectsView', '/projects/ProjectsView', Record<never, never>, Record<never, never>>,
    '/requirements/RequirementDetailsView': RouteRecordInfo<'/requirements/RequirementDetailsView', '/requirements/RequirementDetailsView', Record<never, never>, Record<never, never>>,
    '/requirements/RequirementsView': RouteRecordInfo<'/requirements/RequirementsView', '/requirements/RequirementsView', Record<never, never>, Record<never, never>>,
    '/settings/SettingsView': RouteRecordInfo<'/settings/SettingsView', '/settings/SettingsView', Record<never, never>, Record<never, never>>,
    '/test-plans/TestPlanDetailsView': RouteRecordInfo<'/test-plans/TestPlanDetailsView', '/test-plans/TestPlanDetailsView', Record<never, never>, Record<never, never>>,
    '/test-plans/TestPlansView': RouteRecordInfo<'/test-plans/TestPlansView', '/test-plans/TestPlansView', Record<never, never>, Record<never, never>>,
    '/test-runs/TestRunDetailsView': RouteRecordInfo<'/test-runs/TestRunDetailsView', '/test-runs/TestRunDetailsView', Record<never, never>, Record<never, never>>,
    '/test-runs/TestRunsView': RouteRecordInfo<'/test-runs/TestRunsView', '/test-runs/TestRunsView', Record<never, never>, Record<never, never>>,
    '/test-suites/TestSuiteDetailsView': RouteRecordInfo<'/test-suites/TestSuiteDetailsView', '/test-suites/TestSuiteDetailsView', Record<never, never>, Record<never, never>>,
    '/test-suites/TestSuitesView': RouteRecordInfo<'/test-suites/TestSuitesView', '/test-suites/TestSuitesView', Record<never, never>, Record<never, never>>,
  }
}
