/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/DashboardView': RouteRecordInfo<'/DashboardView', '/DashboardView', Record<never, never>, Record<never, never>>,
    '/MembersView': RouteRecordInfo<'/MembersView', '/MembersView', Record<never, never>, Record<never, never>>,
    '/ProjectsView': RouteRecordInfo<'/ProjectsView', '/ProjectsView', Record<never, never>, Record<never, never>>,
    '/SettingsView': RouteRecordInfo<'/SettingsView', '/SettingsView', Record<never, never>, Record<never, never>>,
  }
}
