# Generated by Django 4.0.4 on 2022-05-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0002_people_accepted_people_invited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='author',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='users',
        ),
        migrations.DeleteModel(
            name='AccountHolders',
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
