# Generated by Django 4.0.4 on 2022-05-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0003_remove_administrator_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.ImageField(default='', upload_to='media/logo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
