# Generated by Django 4.0.4 on 2022-05-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_tracker", "0003_alter_testcases_verify_requirement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testplan",
            name="temps",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
