# Generated by Django 4.0.4 on 2022-05-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0004_user_logo_delete_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='logo',
        ),
    ]
