# Generated by Django 4.0.4 on 2022-05-22 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0005_alter_testplan_temps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
    ]
