# Generated by Django 4.0.4 on 2022-05-22 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_tracker", "0006_rename_name_project_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testcases",
            name="assigned_user",
        ),
        migrations.RemoveField(
            model_name="testcases",
            name="status",
        ),
        migrations.AddField(
            model_name="testrun",
            name="assigned_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_run_assigned_user",
                to="test_tracker.member",
            ),
        ),
        migrations.AddField(
            model_name="testrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("not_started", "not started"),
                    ("in_progress", "in progress"),
                    ("completed", "completed"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="testcases",
            name="verify_requirement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verifies_requirements",
                to="test_tracker.requirements",
            ),
        ),
    ]
