# Generated by Django 4.0.4 on 2022-05-24 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_tracker", "0007_remove_testcases_assigned_user_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProjectRequirement",
            new_name="RequirementDocs",
        ),
        migrations.AddField(
            model_name="testsuites",
            name="test_plan",
            field=models.ForeignKey(
                default=11,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_plan_test_suites",
                to="test_tracker.testplan",
            ),
            preserve_default=False,
        ),
    ]
