# Generated by Django 4.0.4 on 2022-05-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_tracker", "0008_rename_projectrequirement_requirementdocs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirements",
            name="requirement_title",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testcases",
            name="testcase_title",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
