# Generated by Django 4.0.4 on 2022-05-13 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0008_remove_people_email_remove_people_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='invited_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
