# Generated by Django 4.0.4 on 2022-05-24 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0009_requirements_requirement_title_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testcases',
            unique_together={('id', 'testcase_title')},
        ),
    ]
