# Generated by Django 4.0.4 on 2022-05-13 21:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0009_alter_people_invited_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteSignature',
            fields=[
                ('signature', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('json_data', models.JSONField(default={})),
            ],
        ),
    ]
