# Generated by Django 4.0.4 on 2022-05-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_tracker", "0010_alter_testcases_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="testcases",
            unique_together=set(),
        ),
    ]
