# Generated by Django 4.0.4 on 2022-05-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0010_invitesignature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitesignature',
            name='json_data',
            field=models.JSONField(default=dict),
        ),
    ]
