# Generated by Django 4.0.4 on 2022-05-13 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0011_alter_invitesignature_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitesignature',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitesignature',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
