# Generated by Django 4.0.4 on 2022-05-13 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0012_invitesignature_created_invitesignature_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='signature',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='test_tracker.invitesignature'),
            preserve_default=False,
        ),
    ]
