# Generated by Django 4.0.4 on 2022-05-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0012_testcases_unique_testcase_title_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='testcases',
            name='unique_testcase_title_id',
        ),
        migrations.AddField(
            model_name='project',
            name='REQ_TC_Title',
            field=models.JSONField(default=dict),
        ),
    ]
