# Generated by Django 4.0.4 on 2022-05-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0016_alter_project_req_tc_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='REQ_TC_Title',
            new_name='REQ_Title',
        ),
        migrations.AddField(
            model_name='project',
            name='TC_Title',
            field=models.JSONField(default=list),
        ),
    ]
