# Generated by Django 4.0.4 on 2022-05-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0019_alter_testplan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='activity',
            field=models.JSONField(default=dict),
        ),
    ]
