# Generated by Django 4.0.4 on 2022-05-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0021_alter_testrun_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='status',
            field=models.CharField(choices=[('not_started', 'not started'), ('in_progress', 'in progress'), ('completed', 'completed')], default='not_started', max_length=100),
        ),
    ]
