# Generated by Django 4.0.4 on 2022-06-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_tracker", "0022_alter_testrun_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="short_description",
            field=models.TextField(default="", max_length=500),
            preserve_default=False,
        ),
    ]
