# Generated by Django 4.0.4 on 2022-05-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0022_remove_project_users_project_user_user_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='people',
        ),
    ]
