# Generated by Django 4.0.4 on 2022-05-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0023_remove_user_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='invited_user',
        ),
        migrations.RemoveField(
            model_name='people',
            name='signature',
        ),
        migrations.AddField(
            model_name='people',
            name='email',
            field=models.EmailField(default='', max_length=70, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='first_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='last_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
