# Generated by Django 4.0.4 on 2022-05-15 10:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0024_remove_people_invited_user_remove_people_signature_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InviteSignature',
        ),
        migrations.RemoveField(
            model_name='people',
            name='id',
        ),
        migrations.AddField(
            model_name='people',
            name='signature',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
