# Generated by Django 4.0.4 on 2022-06-18 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_tracker", "0025_alter_testcases_verify_requirement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcases",
            name="last_saved",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="last_saved_test_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
