# Generated by Django 4.0.4 on 2022-05-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0025_delete_invitesignature_remove_people_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
