# Generated by Django 4.0.4 on 2022-05-15 12:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0026_people_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='people',
            name='signature',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
