# Generated by Django 4.0.4 on 2022-05-15 12:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0027_people_id_alter_people_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='signature',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
