# Generated by Django 4.0.4 on 2022-05-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0028_alter_people_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='password',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
