# Generated by Django 4.0.4 on 2022-12-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0029_alter_testplan_temps'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_pass',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
