# Generated by Django 4.0.4 on 2022-12-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_tracker", "0030_user_github_pass"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="github_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
