# Generated by Django 4.0.4 on 2022-05-16 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0030_projectrequirement_requirements_delete_requirement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectrequirement',
            options={'verbose_name': 'Requirement', 'verbose_name_plural': 'Requirements'},
        ),
        migrations.AlterModelOptions(
            name='requirements',
            options={},
        ),
        migrations.RemoveField(
            model_name='projectrequirement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projectrequirement',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='project',
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_requirements', to='test_tracker.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requirements',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='requirements',
            name='requirement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_requirement', to='test_tracker.projectrequirement'),
            preserve_default=False,
        ),
    ]
