# Generated by Django 4.0.4 on 2022-12-01 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0031_user_github_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='github_pass',
        ),
    ]
