# Generated by Django 4.0.4 on 2022-12-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0032_remove_user_github_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github_token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
