# Generated by Django 4.0.4 on 2022-05-16 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0032_alter_projectrequirement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirements',
            options={'verbose_name': 'Requirement', 'verbose_name_plural': 'Requirement'},
        ),
    ]
