# Generated by Django 4.0.4 on 2022-12-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0033_alter_user_github_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
