# Generated by Django 4.0.4 on 2022-12-14 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_tracker", "0035_testsuitessection_testsuites_sections"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testsuites",
            name="sections",
        ),
        migrations.AddField(
            model_name="testsuitessection",
            name="test_suites",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="section_test_suites",
                to="test_tracker.testsuites",
            ),
        ),
    ]
