# Generated by Django 4.0.4 on 2022-05-16 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0036_testcases_test_suite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcases',
            name='verifies_requirements',
        ),
        migrations.AddField(
            model_name='testcases',
            name='verify_requirement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='verifies_requirements', to='test_tracker.requirements'),
            preserve_default=False,
        ),
    ]
