# Generated by Django 4.0.4 on 2022-05-16 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0037_remove_testcases_verifies_requirements_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcases',
            options={'verbose_name': 'TestCase', 'verbose_name_plural': 'TestCases'},
        ),
        migrations.AddField(
            model_name='testcases',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='testcases',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testcases',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testcases',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('', ''), ('not_started', 'not started'), ('in_progress', 'in progress'), ('completed', 'completed')], default='', max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_user', to=settings.AUTH_USER_MODEL)),
                ('suites', models.ManyToManyField(related_name='run_suites', to='test_tracker.testsuites')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
