# Generated by Django 4.0.4 on 2022-05-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0038_alter_testcases_options_testcases_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testrun',
            old_name='suites',
            new_name='test_suites',
        ),
    ]
