# Generated by Django 4.0.4 on 2022-05-16 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0039_rename_suites_testrun_test_suites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='assigned_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_user', to='test_tracker.people'),
        ),
    ]
