# Generated by Django 4.0.4 on 2022-05-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0040_alter_testrun_assigned_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcases',
            name='run',
            field=models.BooleanField(default=False),
        ),
    ]
