# Generated by Django 4.0.4 on 2022-05-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0041_testcases_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrun',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='status',
        ),
        migrations.AddField(
            model_name='testcases',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testcases',
            name='status',
            field=models.CharField(choices=[('', ''), ('not_started', 'not started'), ('in_progress', 'in progress'), ('completed', 'completed')], default='', max_length=100),
        ),
    ]
